<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0-android</TargetFramework>
    <NoWarn>$(NoWarn);NETSDK1202</NoWarn>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <DefineConstants>$(DefineConstants);ANDROID</DefineConstants>
    <RootNamespace>TWP_Android</RootNamespace>
    <AssemblyName>TWP_Android</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <ApplicationId>com.example.twpandroid</ApplicationId>
    <AndroidUseLatestPlatformSdk>false</AndroidUseLatestPlatformSdk>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\TWPBaseLib\TWPBaseLib.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.Android" Version="3.8.2.29-day" />
    <PackageReference Include="Xamarin.Legacy.OpenTK" Version="1.0.0" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\TWP Shared\**\*.cs" Exclude="..\TWP Shared\obj\**;..\TWP Shared\bin\**" />
    <Compile Include="ActivityMain.cs" />
    <Compile Include="Resources\Resource.Designer.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
  </ItemGroup>
  <ItemGroup>
    <AndroidResource Include="Resources\Values\Strings.xml" />
    <AndroidResource Include="Resources\Drawable\Icon.png" />
    <AndroidResource Include="Resources\Values\Styles.xml" />
    <AndroidResource Include="Resources\Values\Colors.xml" />
    <AndroidResource Include="Resources\Drawable\Splash.xml" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Properties\AndroidManifest.xml" />
    <None Include="Resources\AboutResources.txt" />
    <None Include="Assets\AboutAssets.txt" />
  </ItemGroup>
</Project>
