<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>TWP_Desktop</RootNamespace>
    <AssemblyName>The Witness Puzzles</AssemblyName>
    <UseWPF>false</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>Icon.ico</ApplicationIcon>
    <StartupObject>TWP_Desktop.Program</StartupObject>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\TWPBaseLib\TWPBaseLib.csproj.sdk" />
    <ProjectReference Include="..\TWP Shared\TWP_Shared.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.1.303" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="Program.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Icon.ico" />
    <None Include="app.config" />
    <None Include="app.manifest" />
  </ItemGroup>
</Project>

